### ISSUE TITLE
pgmodeler 1.1.1 crashes after diff

### ISSUE THREAD

**Issue by darko1979** [pgmodeler/pgmodeler#1872]
**Bug description**
Since pgmodeler v1.1.1 after performing diff and closing diff dialog pgmodeler crashes. There is noting in the report or stack trace.

**Screenshots**
![image](https://github.com/pgmodeler/pgmodeler/assets/23734311/4de26550-a09f-422f-8fe4-880c68036437)
![image](https://github.com/pgmodeler/pgmodeler/assets/23734311/b5e8a423-b911-442a-9886-8ed5b250f443)

**Info about your desktop**
 - OS: Windows 10
 - Version: 22H2
 - pgModeler version: 1.1.1
 - Qt version: 6.4.2

**Stacktrace / Debug info**
```
** pgModeler crashed after receive signal: 11 **

Date/Time: 2024-04-05 14:41:39 
Version: 1.1.1 
Build: 20240318.20240318 
Compilation Qt version: 6.4.2
Running Qt version: 6.4.2

** Stack trace unavailable on Windows system **```

**Additional info**
This started happening after upgrading to 1.1.1, before it never crashed on diff.

**Comment by pms967** [comment]
> A sample database in which the crash happens will help me a lot to find out what is going on! :)

Sure thing. How / where can I send you the .dbm file? 

BTW: run from the command line, right before crashing it writes: “corrupted double-linked list”.  I doubt that's much useful, though.  :-)

**Comment by darko1979** [comment]
First time I reported this issue I tried creating a sample schema that caused it because I could not attach the schema that I was working on (it was not mine to share).

This time I managed to create a schema (with all randomized names) that will produce the issue. Sometimes it would happen that the same schema will crash pgmodeler and then when I try it again it does not. 
Attached schema crashed pgmodeler 1.1.6 twice in a row.

Attached file is a database dump, just rename it to test1.sql and restore it. Then create another empty database called test2.
In pgmodeler choose diff and select to compare test1 and test2. After diff is complete click cancel and then close. Pgmodeler should crash.

[test1.txt](https://github.com/user-attachments/files/18655423/test1.txt)

**Comment by pms967** [comment]
Update: I have locally rebuilt (on Debian 12) pgmodeler (1.1.5) using the source deb package from Debian unstable (that is I "backported" the Sid package).  Just in case I've also deleted the old config files and directories under my home dir before starting the new version.

Now the crash no longer happens (using the very same project file and live DB, of course).

While it may be that the problem was somehow fixed in the newer release, I suspect that the problem may have been caused by an update of some of the pgmodeler dependencies, and what solved it could have been the fresh local rebuild rather than the newer release.

This because the crash problem appeared only recently, all of a sudden.  It did not manifest itself previously, despite using the same pgmodeler version (1.0.0~beta1-1) on the same system, also working on the same project (though not exactly the same, as meanwhile I had made some minor changes here and there). 

Hope it helps.

**Comment by darko1979** [comment]
Crash still happens on v1.2.0
Tested with the sample I provided on my previous comment.
